src/GalleriesBundle/Entity/Gallery.php
<?php

namespace GalleriesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\Entity as Entity;

/**
 * Gallery
 */
class Gallery extends Entity
{
    /**
     * @var integer
     */
    private $id;
    
    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $body;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var \DateTime
     */
    private $deletedAt;

    
    
    
    protected $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set objectId
     *
     * @param integer $objectId
     * @return Gallery
     */
    public function setObjectId($objectId)
    {
        $this->objectId = $objectId;

        return $this;
    }

    /**
     * Get objectId
     *
     * @return integer 
     */
    public function getObjectId()
    {
        return $this->objectId;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Gallery
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set body
     *
     * @param string $body
     * @return Gallery
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get body
     *
     * @return string 
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Gallery
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Gallery
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set deletedAt
     *
     * @param \DateTime $deletedAt
     * @return Gallery
     */
    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * Get deletedAt
     *
     * @return \DateTime 
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }
    
    public function getImages()
    {
        return $this->images;
    }
    
    public function getFirstImage()
    {
        return $this->images[0];
    }
}

src/GalleriesBundle/Controller/DefaultController.php
<?php

namespace Kit\GalleriesBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $galleries = $em->getRepository('KitGalleriesBundle:Gallery')
                       ->findAll();
        
        return $this->render('KitGalleriesBundle:Default:index.html.twig', array(
            'galleries' => $galleries
        ));
    }
    
    public function viewAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $gallery = $em->getRepository('KitGalleriesBundle:Gallery')
                       ->findOneById($id);
        
        return $this->render('KitGalleriesBundle:Default:view.html.twig', array(
                    'gallery' => $gallery
        ));
    }
}

src/GalleriesBundle/Resources/views/Default/index.html.twig
{% set disableRightMenu = true %}

{% extends "KitSystemBundle::layout.html.twig" %}

{% block title "" %}

{% block content_header '' %}

{% block content %}

        <div class="section section_with_padding" id="testimonial"> 
            <h2>Примеры работ</h2>
            <p><em>Aliquam venenatis, quam a semper blandit, lectus mi convallis orci, ut dictum ante leo non leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat, urna in gravida rhoncus, mi elit luctus nibh, a luctus erat elit vel quam. </em></p>
            
            <div class="clear h40"></div>
            
            {% for key, item in galleries %}
                <div class="half {% if key%2 == 0 %}left{% else %}right{% endif %}">
                    <div class="img_border img_fl">
                        <a href="{{ path('_gallery_view', {'id': item.id}) }}">
                            <img src="/uploads/galleries/{{ item.firstImage.image }}" width="80px" alt="image 1">
                        </a>
                    </div>
                    {{ item.body | raw }}
                    <cite>{{ item.title }}</cite>
                </div>
            {% endfor %}
        </div>
    
        <div class="clear h40"></div>
    
{% endblock %}

src/GalleriesBundle/Resources/views/Default/view.html.twig
{% set disableRightMenu = true %}

{% extends "KitSystemBundle::layout.html.twig" %}

{% block title "" %}

{% block head %}
    <link rel="stylesheet" type="text/css" media="all" href="{{ asset('bundles/system/css/lightbox.css') }}">
    <script src="{{ asset('bundles/system/js/lightbox.min.js') }}"></script>
{% endblock %}
    
{% block content_header '' %}

{% block content %}

        <div class="section section_with_padding" id="testimonial"> 
            <h2>{{ gallery.title }}</h2>
            <p><em>{{ gallery.body | raw }}</em></p>
            
            <div class="clear h40"></div>
            <div id="home_gallery" class="box no_mr">
                {% for item in gallery.images %}
                    <a href="/uploads/galleries/{{ item.image }}" data-lightbox="gallery">
                        <img src="/uploads/galleries/{{ item.image }}" width="152px">
                    </a>
                {% endfor %}
            </div>
        </div>
    
        <div class="clear h40"></div>
    
{% endblock %}